# Generated by Django 6.0.2 on 2026-03-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domain')),
                ('business', models.TextField(blank=True, null=True, verbose_name='Business Field')),
                ('founded', models.IntegerField(blank=True, null=True, verbose_name='Established Year')),
                ('capital', models.CharField(blank=True, max_length=100, null=True, verbose_name='Capital')),
                ('employees', models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Count')),
                ('headquarter', models.CharField(blank=True, max_length=255, null=True, verbose_name='Headquarter')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='Logo URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
    ]
