# Generated by Django 6.0.2 on 2026-03-06 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Job Title')),
                ('job_type', models.CharField(choices=[('fulltime', 'Full-time'), ('contract', 'Contract'), ('parttime', 'Part-time'), ('intern', 'Intern')], default='fulltime', max_length=20)),
                ('salary', models.CharField(blank=True, max_length=100, null=True, verbose_name='Salary')),
                ('salary_min', models.IntegerField(blank=True, null=True, verbose_name='Salary Min (JPY)')),
                ('salary_max', models.IntegerField(blank=True, null=True, verbose_name='Salary Max (JPY)')),
                ('benefits', models.TextField(blank=True, null=True, verbose_name='Benefits')),
                ('vacation_days', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vacation Days')),
                ('remote', models.CharField(choices=[('full_remote', 'Full Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('tech_stack', models.JSONField(blank=True, default=list, verbose_name='Tech Stack')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Job Description')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Requirements')),
                ('source_url', models.URLField(verbose_name='Source URL')),
                ('source_name', models.CharField(max_length=50, verbose_name='Source Site')),
                ('is_ai_related', models.BooleanField(default=False, verbose_name='AI Related')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company.company')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_type', models.CharField(choices=[('llm_engineer', 'LLM Engineer'), ('ml_engineer', 'Machine Learning Engineer'), ('dl_engineer', 'Deep Learning Engineer'), ('ai_agent_engineer', 'AI Agent Engineer'), ('data_scientist', 'Data Scientist'), ('cv_engineer', 'Computer Vision Engineer'), ('nlp_engineer', 'NLP Engineer'), ('ai_researcher', 'AI Researcher'), ('generative_ai', 'Generative AI Engineer')], max_length=50)),
                ('ai_tech_stack', models.JSONField(blank=True, default=list, verbose_name='AI Tech Stack')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_jobs', to='job.job')),
            ],
            options={
                'verbose_name': 'AI Job',
                'verbose_name_plural': 'AI Jobs',
                'db_table': 'ai_jobs',
            },
        ),
    ]
